#!/bin/sh --
set -ex
SCRIPT_DIR="$(cd -- "${0%/*}/" && pwd)"
. "$SCRIPT_DIR/../../hc/core/shell/recipe.sh"

DEPENDENCIES="llvm hc"
DIR_DEPENDENCIES="../utilities"

recipe_start
export LLVM="$OUT/llvm"
export ARCH=x86_64
export ABI=linux
export FLAGS="-Werror -Os"
export FLAGS_RELEASE= FLAGS_DEBUG=

for utility in bootstrap clangCompilerWrapper clangWrapper coreutilsWrapper env libcSoWrapper lldWrapper sh shWrapper shell; do
    OUT="$OUT/$SCRIPT_NAME" "$SCRIPT_DIR/../../hc/core/builder.sh" "$SCRIPT_DIR/../utilities/$utility.c"
    "$SCRIPT_DIR/../../hc/core/objcopy.sh" --strip-sections "$OUT/$SCRIPT_NAME/$ARCH-${ABI}_$utility"
    touch -t 197001010000 "$OUT/$SCRIPT_NAME/$ARCH-${ABI}_$utility"
    touch -t 197001010000 "$OUT/$SCRIPT_NAME/debug/$ARCH-${ABI}_$utility"
done

recipe_finish
